[project]
name = "fastapi-zero"
version = "0.1.0"
description = ""
authors = [
    {name = "ester-17",email = "139085601+ester-17@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.13,<4.0"
dependencies = [
    "fastapi[standard] (>=0.118.0,<0.119.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
